
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 25666524qq
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connect-properties:
        druid:
          stat:
            mergeSql: true
            slowSqlMillis: 5000
      valid-connection-checker-class-name: com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.example.blog.entity
  mapper-locations: classpath:mapper/*.xml